sudo docker run -d \
  --restart=unless-stopped \
  --name=kuboard \
  -p 10080:80/tcp \
  -p 20081:10081/tcp \
  -e KUBOARD_ENDPOINT="http://kuboard.k8s.hs.com" \
  -e KUBOARD_AGENT_SERVER_TCP_PORT="20081" \
  -v /data/kuboard-data:/data \
  -e KUBOARD_LOGIN_TYPE="ldap" \
  -e KUBOARD_ROOT_USER="0799" \
  -e LDAP_HOST="192.168.10.250:389" \
  -e LDAP_SKIP_SSL_VERIFY="true" \
  -e LDAP_BIND_DN="CN=域管理员,OU=Services,OU=Headquarter,dc=hs,dc=com" \
  -e LDAP_BIND_PASSWORD="ops@1qa2ws" \
  -e LDAP_BASE_DN="OU=技术研发中心,OU=部门员工,OU=Users,OU=Headquarter,DC=hs,DC=com" \
  -e LDAP_FILTER="(objectClass=user)" \
  -e LDAP_ID_ATTRIBUTE="sAMAccountName" \
  -e LDAP_USER_NAME_ATTRIBUTE="sAMAccountName" \
  -e LDAP_EMAIL_ATTRIBUTE="mail" \
  -e LDAP_DISPLAY_NAME_ATTRIBUTE="displayName" \
  -e LDAP_GROUP_SEARCH_BASE_DN="OU=Roles,OU=Groups,OU=Headquarter,DC=hs,DC=com" \
  -e LDAP_GROUP_SEARCH_FILTER="(objectClass=group)" \
  -e LDAP_USER_MACHER_USER_ATTRIBUTE="memberOf" \
  -e LDAP_USER_MACHER_GROUP_ATTRIBUTE="DistinguishedName" \
  -e LDAP_GROUP_NAME_ATTRIBUTE="name" \
  harborrepo.hs.com/ops/kuboard:v3
